# Generated by Django 4.1.7 on 2023-12-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_adres_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
