# Generated by Django 4.1.7 on 2023-12-06 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloggger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('contact', models.IntegerField()),
                ('profile_pic', models.ImageField(default='', upload_to='user_profile')),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vender',
                'verbose_name_plural': 'vender',
            },
        ),
    ]
