# Generated by Django 4.1.7 on 2023-12-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_bloggger_blogger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='address',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
