# Generated by Django 4.1.7 on 2023-12-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='payment_mode',
            field=models.CharField(default='Cash on delivery', max_length=20),
        ),
    ]
